# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

In [2]:
import numpy as np

# Numpy Arrays


Creating

In [51]:
#from list
my_list = [1,2,3,4]
np.array(my_list)

array([1, 2, 3, 4])

In [52]:
#from lists
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)
#if inconsistent number of entries it will be array of lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
#range
print(np.arange(0,10))
print('--------------------------------')
print(np.arange(0,10,2))

[0 1 2 3 4 5 6 7 8 9]
--------------------------------
[0 2 4 6 8]


In [54]:
#zeros/ones
print(np.zeros((5,5)))
print('--------------------------------')
print(np.ones(2))


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
--------------------------------
[1. 1.]


In [55]:
#linspace 
#return evenly spaced numbers over a specified interval
print(np.linspace(0,10,50))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [56]:
# eye 
#creates an identity matrix
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


random

In [57]:
np.random.rand(5,5)

array([[0.52522402, 0.20413072, 0.99638418, 0.26519768, 0.93037873],
       [0.56534636, 0.11069037, 0.56687352, 0.41397466, 0.66688756],
       [0.93504408, 0.09055471, 0.70838114, 0.65915986, 0.35125929],
       [0.1257852 , 0.44827004, 0.68684164, 0.78806938, 0.17831926],
       [0.18925868, 0.40078926, 0.5386693 , 0.74184371, 0.84397664]])

In [58]:
# rand
# create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
print(np.random.rand(5,5))
print('--------------------------------')
# randn
# Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:
print(np.random.randn(4,4))
print('--------------------------------')
# randint
# Return random integers from `low` (inclusive) to `high` (exclusive).
print(np.random.randint(1,100,(10,2)))

[[0.11981382 0.13235726 0.76908127 0.4728028  0.82681844]
 [0.33070102 0.86241421 0.26687602 0.48647207 0.34284141]
 [0.30129734 0.02405904 0.90970721 0.19704992 0.3263003 ]
 [0.54395827 0.16655474 0.56574699 0.97998851 0.49256578]
 [0.50809966 0.43201552 0.96238336 0.78268426 0.06419076]]
--------------------------------
[[ 1.89519527  0.84838872 -0.50906734 -1.55045323]
 [-0.58026591 -0.88664656 -2.24431516  0.44944112]
 [-1.89286182 -0.8985755   0.21785839  0.715131  ]
 [ 0.32812131  0.47709141  1.88321247 -0.48840989]]
--------------------------------
[[38 18]
 [82 62]
 [38 73]
 [14 77]
 [34 41]
 [95 45]
 [ 1  8]
 [91 11]
 [96 97]
 [58 50]]


Build-in methods

reshape

In [59]:
arr = np.arange(25)
print(arr)
print('--------------------------------')
print(arr.reshape(5,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
--------------------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


max,min,argmax,argmin

In [60]:
ranarr = np.random.randint(0,50,10)
print(ranarr)
print('--------------------------------')
print(ranarr.max())
print('--------------------------------')
print(ranarr.argmax())
print('--------------------------------')
print(ranarr.min())
print('--------------------------------')
print(ranarr.argmin())

[26 31 14  9 49  7 30 42 39 43]
--------------------------------
49
--------------------------------
4
--------------------------------
7
--------------------------------
5


shape,dtype,info

In [61]:
print(ranarr)
print('--------------------------------')
print(ranarr.shape)
print('--------------------------------')
print(ranarr.reshape(5,2))
print('--------------------------------')
print(ranarr.reshape(5,2).shape)
print('--------------------------------')
print(ranarr.dtype)
print('--------------------------------')
print(ranarr.size)

[26 31 14  9 49  7 30 42 39 43]
--------------------------------
(10,)
--------------------------------
[[26 31]
 [14  9]
 [49  7]
 [30 42]
 [39 43]]
--------------------------------
(5, 2)
--------------------------------
int64
--------------------------------
10


data types

In [4]:
# A structured data type containing a 16-character string (in field ‘name’)  
# and a sub-array of two 64-bit floating-point number (in field ‘grades’): 
  
dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2,))]) 
  
# Data type of object with field grades 
print(dt['grades']) 
  
# Data type of object with field name  
print(dt['name']) 

# x is a structured array with names and marks of students. 
# Data type of name of the student is np.unicode_ and  
# data type of marks is np.float(64) 
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0))], dtype=dt) 
  
print(x[1]) 
print("Grades of John are: ",x[1]['grades']) 
print("Names are: ",x['name']) 

('<f8', (2,))
<U16
('John', [6., 7.])
Grades of John are:  [6. 7.]
Names are:  ['Sarah' 'John']


# Indexing and selection

### indexing

simple bracket indexing

In [5]:
arr = np.arange(0,11)
print(arr[:])
print('--------------------------------')
print(arr[8])
print('--------------------------------')
print(arr[2:4]) #without last
print('--------------------------------')
print(arr[:-1])
print('--------------------------------')
print(arr[-2:])

[ 0  1  2  3  4  5  6  7  8  9 10]
--------------------------------
8
--------------------------------
[2 3]
--------------------------------
[0 1 2 3 4 5 6 7 8 9]
--------------------------------
[ 9 10]


changing

In [63]:
arr = np.arange(0,11)
arr[0:5]=100
print(arr)
print('--------------------------------')
slice_of_arr = arr[0:6] #shallow reference
print(slice_of_arr)
print('--------------------------------')
slice_of_arr[:]=10
print(arr)
print('--------------------------------')
slice_of_arr_2 = arr[0:6].copy() #deep reference
print(slice_of_arr_2)
print('--------------------------------')
slice_of_arr_2[:]=1000
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]
--------------------------------
[100 100 100 100 100   5]
--------------------------------
[10 10 10 10 10 10  6  7  8  9 10]
--------------------------------
[10 10 10 10 10 10]
--------------------------------
[10 10 10 10 10 10  6  7  8  9 10]


In [9]:
#2D
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
print(arr_2d)
print('--------------------------------')
print(arr_2d[1])
print('--------------------------------')
print(arr_2d[2][1])
print('--------------------------------')
print(arr_2d[:2,1:]) #shape (2,2) from top right corner
print('--------------------------------')
print(arr_2d[[2,1]]) #allows in any ordr
print('--------------------------------')
print(arr_2d[[2],[0,2]]) #allows in any ordr
print('--------------------------------')
print(arr_2d[2,1]) #allows in any ordr

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
--------------------------------
[20 25 30]
--------------------------------
40
--------------------------------
[[10 15]
 [25 30]]
--------------------------------
[[35 40 45]
 [20 25 30]]
--------------------------------
[35 45]
--------------------------------
40


### selecting

In [65]:
arr = np.arange(1,11)
print(arr)
print('--------------------------------')
print(arr > 4)
print('--------------------------------')
bool_arr = arr>4
print(arr[bool_arr])
print('--------------------------------')
print(arr[arr>4])

[ 1  2  3  4  5  6  7  8  9 10]
--------------------------------
[False False False False  True  True  True  True  True  True]
--------------------------------
[ 5  6  7  8  9 10]
--------------------------------
[ 5  6  7  8  9 10]


### iterating

In [18]:
# creating an array using arrange 
# method
a = np.arange(12)
 
# shape array with 3 rows and 
# 4 columns 
a = a.reshape(3,4)
print('Original array is:')
print(a)
print()
 
# modifying array values
for x in np.nditer(a, op_flags = ['readwrite']): #without flag Valuererror
    x[...] = 5*x
print('Modified array is:')
print(a)

Original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Modified array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


### Sort

In [28]:
# sort along the first axis
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)        
print ("Along first axis : \n", arr1)        
 
 
# sort along the last axis
a = np.array([[10, 15], [12, 1]])
arr2 = np.sort(a, axis = -1)        
print ("\nAlong first axis : \n", arr2)
 
 
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = None)        
print ("\nAlong none axis : \n", arr1)

Along first axis : 
 [[10  1]
 [12 15]]

Along first axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]


# Operations

basic

In [66]:
arr = np.arange(0,10)
print(arr + arr)
print('--------------------------------')
print(arr * arr)
print('--------------------------------')
print(arr - arr)
print('--------------------------------')
print(arr/arr)
print('--------------------------------')
print(1/arr)
print('--------------------------------')
print(arr**3)

[ 0  2  4  6  8 10 12 14 16 18]
--------------------------------
[ 0  1  4  9 16 25 36 49 64 81]
--------------------------------
[0 0 0 0 0 0 0 0 0 0]
--------------------------------
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]
--------------------------------
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]
--------------------------------
[  0   1   8  27  64 125 216 343 512 729]


/usr/lib/python3/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in true_divide
  
/usr/lib/python3/dist-packages/ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in true_divide
  # Remove the CWD from sys.path while we load stuff.


numpay's

In [67]:
print(np.sqrt(arr))
print('--------------------------------')
print(np.exp(arr))
print('--------------------------------')
print(np.max(arr))
print('--------------------------------')
print(np.sqrt(arr))
print('--------------------------------')
print(np.log(arr))
print('--------------------------------')
print(np.sin(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
--------------------------------
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
--------------------------------
9
--------------------------------
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
--------------------------------
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]
--------------------------------
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


/usr/lib/python3/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


matrix

In [11]:
arr_2d = np.array(([5,10,15],
                   [20,25,30],
                   [35,40,45]))
print(np.matmul(arr_2d,arr_2d))
print('--------------------------------')
print(np.dot(arr_2d,arr_2d)) #same, less options
print('--------------------------------')
print(np.transpose(arr_2d))
print('--------------------------------')
print(np.linalg.norm(arr_2d))
print('--------------------------------')
print(np.linalg.matrix_power(arr_2d, 3))
print('--------------------------------')

[[ 750  900 1050]
 [1650 2025 2400]
 [2550 3150 3750]]
--------------------------------
[[ 750  900 1050]
 [1650 2025 2400]
 [2550 3150 3750]]
--------------------------------
[[ 5 20 35]
 [10 25 40]
 [15 30 45]]
--------------------------------
84.40971508067067
--------------------------------
[[ 58500  72000  85500]
 [132750 163125 193500]
 [207000 254250 301500]]
--------------------------------


# Examples

From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

In [27]:
# Input
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, (2,20))
print(a)
print('-----------------------')
# Solution 1: Using np.clip
print(np.clip(a, a_min=10, a_max=30))
print('-----------------------')
# Solution 2: Using np.where
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))
print('-----------------------')
# Solution 3:
a[a>30] = 30
a[a<10] = 10
print(a)

[[27.63 14.64 21.8  42.39  1.23  6.96 33.87 41.47  7.7  29.18 44.67 11.25
  10.08  6.31 11.77 48.95 40.77  9.43 41.   14.43]
 [22.15 47.06 41.06 17.47  9.6  19.27  1.28 13.37 39.99  1.75 30.34 30.59
   6.15 19.72  2.79 44.63 49.07  3.94 44.64 29.27]]
-----------------------
[[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
  10.08 10.   11.77 30.   30.   10.   30.   14.43]
 [22.15 30.   30.   17.47 10.   19.27 10.   13.37 30.   10.   30.   30.
  10.   19.72 10.   30.   30.   10.   30.   29.27]]
-----------------------
[[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
  10.08 10.   11.77 30.   30.   10.   30.   14.43]
 [22.15 30.   30.   17.47 10.   19.27 10.   13.37 30.   10.   30.   30.
  10.   19.72 10.   30.   30.   10.   30.   29.27]]
-----------------------
[[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
  10.08 10.   11.77 30.   30.   10.   30.   14.43]
 [22.15 30.   30.   17.47 10.   19.27 10.   13.37 30. 